---
- name: Check prerequisites
  ansible.builtin.include_tasks: preflight.yml

- name: Set role facts
  ansible.builtin.set_fact:
    pip_extra_args: ""
    target_python_version: "python{{ ansible_python.version.major }}.{{ ansible_python.version.minor }}"

- name: Ensure installation directory exists
  ansible.builtin.file:
    path: "{{ p4_switch_exporter_install_dir }}"
    state: directory
    mode: "0755"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
  become: true

- name: Ensure Python virtualenv package is installed
  ansible.builtin.apt:
    name: "{{ target_python_version }}-venv"
    state: present
  become: true

- name: Add custom Pypi index to pip install arguments
  ansible.builtin.set_fact:
    pip_extra_args: "--extra-index-url {{ p4_switch_exporter_pypi_index }}"
  when: p4_switch_exporter_pypi_index

- name: Install ska-ds-psi-prometheus-exporters Python library
  ansible.builtin.pip:
    name: ska-ds-psi-prometheus-exporters
    version: "{{ p4_switch_exporter_version }}"
    extra_args: "-i https://artefact.skao.int/repository/pypi-internal/simple {{ pip_extra_args }}"
    virtualenv: "{{ p4_switch_exporter_install_dir }}"
    virtualenv_command: "{{ ansible_python_interpreter }} -m venv"
  notify:
    - Restart ska-p4-switch-exporter

- name: Create systemd service unit
  ansible.builtin.template:
    src: ska-p4-switch-exporter.service.j2
    dest: "/etc/systemd/system/ska-p4-switch-exporter.service"
    owner: root
    group: root
    mode: "0644"
  become: true
  notify:
    - Restart ska-p4-switch-exporter
