---
xrt_fpga_exporter_version: 0.0.1
xrt_fpga_exporter_install_dir: /opt/skao/ska-xrt-fpga-exporter
xrt_fpga_exporter_xrt_path: /opt/xilinx/xrt

xrt_fpga_exporter_pypi_index:

# Exporter command-line options. An empty value means the CLI uses its own default.
xrt_fpga_exporter_log_level:
xrt_fpga_exporter_web_port:
